Repository parameter1/fusable-websites, pull requests merged in 2022-04, with the labels that each got.

#369 Add support for setting content meter promo codes
  packages/global/components/blocks/content-meter.marko
  packages/global/config/content-meter.js
  packages/global/package.json
  packages/theme-monorail/components/identity-x/content-page-gate.marko
  packages/theme-monorail/package.json
  sites/ccjdigital.com/package.json
  yarn.lock
Labels: 🌐 site: ALL

#371 Load GTM immediately, add GA4 page_view event
  packages/global/components/document.marko
Labels: 🌐 site: ALL

#374 Push a page view event immediately to gtm
  packages/global/components/document.marko
Labels: 🌐 site: ALL

#376 Upgrade dependencies
  packages/global/package.json
  packages/theme-monorail/package.json
  sites/ccjdigital.com/package.json
  yarn.lock
Labels: dependencies

#378 Update IdX/metering dependencies
  packages/global/components/blocks/content-meter.marko
  packages/global/components/document.marko
  packages/global/package.json
  packages/theme-monorail/components/identity-x/content-page-gate.marko
  packages/theme-monorail/package.json
  sites/ccjdigital.com/package.json
  sites/equipmentworld.com/package.json
  sites/hardworkingtrucks.com/package.json
  sites/overdriveonline.com/package.json
  sites/totallandscapecare.com/package.json
  sites/truckersnews.com/package.json
  sites/truckpartsandservice.com/package.json
  yarn.lock
Labels: bug, dependencies

#381 Remove { event: “page_view” } on gtm init
  packages/global/components/document.marko
Labels: 🌐 site: ALL
