Repository parameter1/fusable-websites, pull requests merged in 2023-04, with the labels that each got.

#529 Correctly look for both Pinned and Standard option schedules for total count
  packages/global/components/layouts/content/company.marko
  packages/global/components/layouts/content/default.marko
  packages/global/components/layouts/content/product.marko
  packages/global/components/layouts/website-section/feed.marko
  packages/global/components/layouts/website-section/home.marko
  packages/global/components/layouts/website-section/products.marko
  packages/global/templates/content/contact.marko
  sites/equipmentworld.com/server/templates/website-section/safety-watch.marko
Labels: bug, 🌐 site: ALL

#530 Add encrypted GAM targeting
  docker-compose.yml
  packages/global/components/document.marko
  packages/global/start-server.js
Labels: 🌐 site: ALL

#531 Dep upgrades & remove duplicate vue components be registered.
  packages/global/browser/index.js
  packages/global/browser/track-content-meter.vue
  packages/global/package.json
  sites/ccjdigital.com/package.json
  sites/equipmentworld.com/package.json
  sites/hardworkingtrucks.com/package.json
  sites/overdriveonline.com/package.json
  sites/totallandscapecare.com/package.json
  sites/truckersnews.com/package.json
  sites/truckpartsandservice.com/package.json
  yarn.lock
Labels: bug, dependencies
