Repository parameter1/fusable-websites, pull requests merged in 2024-05, with the labels that each got.

#722 Contractor of the Year 2024
  packages/global/components/blocks/eqw-coty-promo.marko
  sites/equipmentworld.com/server/components/coty-nav.marko
  sites/equipmentworld.com/server/templates/website-section/contractor-of-the-year/index.marko
Labels: 🌐 site: equipmentworld.com

#725 Add additional viewport size
  packages/global/config/gam.js
Labels: 🌐 site: overdriveonline.com

#728 Enforce 4 columns on injected Native-X Card Deck
  packages/global/components/layouts/content/default.marko
Labels: 🌐 site: ALL
